### ISSUE TITLE
Unable To Use SDK With API Tokens

### ISSUE THREAD

**Issue by afoley587** [homanp/superagent-py#2]
# Problem Statement / Overview

Hi there, I'm unable to use the SDK with API Tokens. I keep getting `{'detail': 'Not authenticated'}`. I think it's most likely because the API doesn't seem to accept API Tokens, only bearer auth (https://github.com/homanp/superagent/blob/7e73c21cde43c39c4e83d7ec069e4e0f7ec816c2/app/api/agents.py#L70C50-L70C59)

# Expected Output

I would expect the GET request to return my agent successfully. But, let me know if I'm initializing it incorrectly in my code snippet below.

# Code Snippet

I included a code snippet with how I'm initializing the client
```python
class WrappedSuperagent(object):
    def __init__(self, api_token: str, environment="https://api.superagent.sh"):
        self._client = Superagent(environment=environment, api_key=api_token)

    # Begin Public Methods
    def get_agent(self, agent_id: str) -> typing.Any:
        return self._get_agent(agent_id)        
    # End Public Methods

    # Begin Private Methods
    def _get_agent(self, agent_id: str) -> typing.Any:
        agent = self._client.agent.get_agent(agent_id) #### ---- Error starts here
        return agent
    # End Private Methods
```

Let me know if you need anymore info and I'm happy to add that as well!

**Comment by homanp** [comment]
Thanks for reporting will fix ASAP

**Comment by afoley587** [comment]
Thanks a bunch! great stuff so far!

**Comment by homanp** [comment]
Hey, this is now fixed. Use the `token` param when creating the client!

https://twitter.com/pelaseyed
https://github.com/homanp

________________________________
